### ISSUE TITLE
`testCanBeRotatedInPlaceTeleop()` fails occasionally

### ISSUE THREAD

**Issue by CoolSpy3** [DeepBlueRobotics/DeepBlueSim#111]
[CI Log](https://github.com/DeepBlueRobotics/DeepBlueSim/actions/runs/9916115451/job/27397969850#step:6:1619)

Possibly related to #94.

**Comment by brettle** [comment]
Will probably be fixed by a fix to #101.

**Comment by brettle** [comment]
Presumably fixed by PR #114. Reopen if it is observed again.
