### ISSUE TITLE
Publish a maven package for use by WPILib projects

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/DeepBlueSim#34]
Benefits:
 - WPILib projects no longer need to check the controller jar into git
 - Clear versioning so projects can specify which version they work with
 - PROTOs and the controller jar can be bundled and versioned together

**Comment by brettle** [comment]
Addressed via PR #37. Everything will be in the Gradle plugin which will be published and versioned.

**Comment by CoolSpy3** [comment]
@brettle Do we also want to do this for [https://github.com/DeepBlueRobotics/WPIWebSockets/](https://github.com/DeepBlueRobotics/WPIWebSockets/).

**Comment by brettle** [comment]
I wouldn't make a Gradle plugin for it since it doesn't provide any user-visible functionality on its own. We could potentially make a Maven package for it but it's pretty low priority in my opinion. I'd rather get people using DeepBlueSim than having them trying to use WPIWebSockets directly. Feel free to open an issue on that repo if you think it's worth pursuing.
