### ISSUE TITLE
Encapsulate functionality useful to tests in a library

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/DeepBlueSim#60]
Create a `libdeepbluesim.jar` library that can be added as a dependency to tests in wpilib projects that use DeepBlueSim. The library would encapsulate the functionality currently in [`webotsInit()`](https://github.com/DeepBlueRobotics/DeepBlueSim/blob/ae761b067a89601525da13632096c739ca8a21ed/example/src/systemTest/java/frc/robot/SystemTestRobot.java#L72) along with the implementation of issue #59, providing a simple stable API for tests that want to use DeepBlueSim while also allowing the implementation details to change as needed in the future. Details TBD.

**Comment by brettle** [comment]
@CoolSpy3 are you ok with me including this lib in the plugin (like DeepBlueSim.jar) instead of publishing it separately? It would avoid the work of publishing it and also insure that the 2 jars are always in sync.

**Comment by CoolSpy3** [comment]
That's how I was thinking of doing it :+1:

**Comment by brettle** [comment]
Fixed by PR #74.
