### ISSUE TITLE
Simplify motor protos.

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/DeepBlueSim#83]
Have a singular WPILinearMotor and WPIRotationalMotor that extend their respective base classes and provide a dropdown to select the motor type.

**Comment by brettle** [comment]
@CoolSpy3, how would you feel about using the names `DBSLinearMotor` and `DBSRotationalMotor` instead of `WPILinearMotor` and `WPIRotationalMotor`. The idea would be to convey that they are the motors that work with DeepBlueSim. Also makes it clearer that if there is a bug with the those protos it should be reported to DeepBlueSim, not WPI.

**Comment by CoolSpy3** [comment]
What I might do is rename `WPILinearMotorBase` and `WPIMotorBase` to `DBSLinearMotorBase` and `DBSRotationalMotor` respectively (for the reasons mentioned above), and then name the new classes `(WPI/FRC)[Linear]MotorBase` to indicate that they correspond to FRC motors. Alternatively, I'd also be fine with something like `PreconfiguredDBS[Linear]Motor` if you wanted to make the DBS/WPI distinction more clear.
